
name: Build and Move to Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (if using JS project)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Angular project
        run: |
          ls -ltr
          cd Code
          npm install
          npm run build -- --configuration production --output-path=docs
      
      - name: Commit and push build output
        uses: EndBug/add-and-commit@v9
        with: 
          message: "chore: commit Angular build output"
          push: true

